// Generated by gencpp from file face_read/GetParametersRequest.msg
// DO NOT EDIT!


#ifndef FACE_READ_MESSAGE_GETPARAMETERSREQUEST_H
#define FACE_READ_MESSAGE_GETPARAMETERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_read
{
template <class ContainerAllocator>
struct GetParametersRequest_
{
  typedef GetParametersRequest_<ContainerAllocator> Type;

  GetParametersRequest_()
    {
    }
  GetParametersRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::face_read::GetParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_read::GetParametersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetParametersRequest_

typedef ::face_read::GetParametersRequest_<std::allocator<void> > GetParametersRequest;

typedef boost::shared_ptr< ::face_read::GetParametersRequest > GetParametersRequestPtr;
typedef boost::shared_ptr< ::face_read::GetParametersRequest const> GetParametersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_read::GetParametersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_read::GetParametersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace face_read

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_read::GetParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_read::GetParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::GetParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::GetParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::GetParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::GetParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_read::GetParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::face_read::GetParametersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::face_read::GetParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_read/GetParametersRequest";
  }

  static const char* value(const ::face_read::GetParametersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_read::GetParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::face_read::GetParametersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_read::GetParametersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParametersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_read::GetParametersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::face_read::GetParametersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FACE_READ_MESSAGE_GETPARAMETERSREQUEST_H
