// Generated by gencpp from file face_read/ReadTwoFacesResponse.msg
// DO NOT EDIT!


#ifndef FACE_READ_MESSAGE_READTWOFACESRESPONSE_H
#define FACE_READ_MESSAGE_READTWOFACESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_read
{
template <class ContainerAllocator>
struct ReadTwoFacesResponse_
{
  typedef ReadTwoFacesResponse_<ContainerAllocator> Type;

  ReadTwoFacesResponse_()
    : face_1()
    , face_2()  {
    }
  ReadTwoFacesResponse_(const ContainerAllocator& _alloc)
    : face_1(_alloc)
    , face_2(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _face_1_type;
  _face_1_type face_1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _face_2_type;
  _face_2_type face_2;





  typedef boost::shared_ptr< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadTwoFacesResponse_

typedef ::face_read::ReadTwoFacesResponse_<std::allocator<void> > ReadTwoFacesResponse;

typedef boost::shared_ptr< ::face_read::ReadTwoFacesResponse > ReadTwoFacesResponsePtr;
typedef boost::shared_ptr< ::face_read::ReadTwoFacesResponse const> ReadTwoFacesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_read::ReadTwoFacesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_read::ReadTwoFacesResponse_<ContainerAllocator1> & lhs, const ::face_read::ReadTwoFacesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.face_1 == rhs.face_1 &&
    lhs.face_2 == rhs.face_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_read::ReadTwoFacesResponse_<ContainerAllocator1> & lhs, const ::face_read::ReadTwoFacesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_read

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9258eb66ca62faac6a93b464c913082a";
  }

  static const char* value(const ::face_read::ReadTwoFacesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9258eb66ca62faacULL;
  static const uint64_t static_value2 = 0x6a93b464c913082aULL;
};

template<class ContainerAllocator>
struct DataType< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_read/ReadTwoFacesResponse";
  }

  static const char* value(const ::face_read::ReadTwoFacesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string face_1\n"
"string face_2\n"
"\n"
"\n"
;
  }

  static const char* value(const ::face_read::ReadTwoFacesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.face_1);
      stream.next(m.face_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadTwoFacesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_read::ReadTwoFacesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_read::ReadTwoFacesResponse_<ContainerAllocator>& v)
  {
    s << indent << "face_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.face_1);
    s << indent << "face_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.face_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_READ_MESSAGE_READTWOFACESRESPONSE_H
