// Generated by gencpp from file face_read/ReadTwoFacesRequest.msg
// DO NOT EDIT!


#ifndef FACE_READ_MESSAGE_READTWOFACESREQUEST_H
#define FACE_READ_MESSAGE_READTWOFACESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_read
{
template <class ContainerAllocator>
struct ReadTwoFacesRequest_
{
  typedef ReadTwoFacesRequest_<ContainerAllocator> Type;

  ReadTwoFacesRequest_()
    : side()  {
    }
  ReadTwoFacesRequest_(const ContainerAllocator& _alloc)
    : side(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _side_type;
  _side_type side;





  typedef boost::shared_ptr< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadTwoFacesRequest_

typedef ::face_read::ReadTwoFacesRequest_<std::allocator<void> > ReadTwoFacesRequest;

typedef boost::shared_ptr< ::face_read::ReadTwoFacesRequest > ReadTwoFacesRequestPtr;
typedef boost::shared_ptr< ::face_read::ReadTwoFacesRequest const> ReadTwoFacesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_read::ReadTwoFacesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_read::ReadTwoFacesRequest_<ContainerAllocator1> & lhs, const ::face_read::ReadTwoFacesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.side == rhs.side;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_read::ReadTwoFacesRequest_<ContainerAllocator1> & lhs, const ::face_read::ReadTwoFacesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_read

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69d615a99b3ddce4b1854895f66933a8";
  }

  static const char* value(const ::face_read::ReadTwoFacesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69d615a99b3ddce4ULL;
  static const uint64_t static_value2 = 0xb1854895f66933a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_read/ReadTwoFacesRequest";
  }

  static const char* value(const ::face_read::ReadTwoFacesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string side\n"
;
  }

  static const char* value(const ::face_read::ReadTwoFacesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.side);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadTwoFacesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_read::ReadTwoFacesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_read::ReadTwoFacesRequest_<ContainerAllocator>& v)
  {
    s << indent << "side: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.side);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_READ_MESSAGE_READTWOFACESREQUEST_H
