// Generated by gencpp from file face_read/SetParametersResponse.msg
// DO NOT EDIT!


#ifndef FACE_READ_MESSAGE_SETPARAMETERSRESPONSE_H
#define FACE_READ_MESSAGE_SETPARAMETERSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_read
{
template <class ContainerAllocator>
struct SetParametersResponse_
{
  typedef SetParametersResponse_<ContainerAllocator> Type;

  SetParametersResponse_()
    : feedback()  {
    }
  SetParametersResponse_(const ContainerAllocator& _alloc)
    : feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::face_read::SetParametersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_read::SetParametersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetParametersResponse_

typedef ::face_read::SetParametersResponse_<std::allocator<void> > SetParametersResponse;

typedef boost::shared_ptr< ::face_read::SetParametersResponse > SetParametersResponsePtr;
typedef boost::shared_ptr< ::face_read::SetParametersResponse const> SetParametersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_read::SetParametersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_read::SetParametersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_read::SetParametersResponse_<ContainerAllocator1> & lhs, const ::face_read::SetParametersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_read::SetParametersResponse_<ContainerAllocator1> & lhs, const ::face_read::SetParametersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_read

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_read::SetParametersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_read::SetParametersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::SetParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_read::SetParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::SetParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_read::SetParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_read::SetParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const ::face_read::SetParametersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_read::SetParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_read/SetParametersResponse";
  }

  static const char* value(const ::face_read::SetParametersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_read::SetParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string feedback\n"
"\n"
;
  }

  static const char* value(const ::face_read::SetParametersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_read::SetParametersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetParametersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_read::SetParametersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_read::SetParametersResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_READ_MESSAGE_SETPARAMETERSRESPONSE_H
