// Generated by gencpp from file face_read/SetParameters.msg
// DO NOT EDIT!


#ifndef FACE_READ_MESSAGE_SETPARAMETERS_H
#define FACE_READ_MESSAGE_SETPARAMETERS_H

#include <ros/service_traits.h>


#include <face_read/SetParametersRequest.h>
#include <face_read/SetParametersResponse.h>


namespace face_read
{

struct SetParameters
{

typedef SetParametersRequest Request;
typedef SetParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameters
} // namespace face_read


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::face_read::SetParameters > {
  static const char* value()
  {
    return "771cbc2cb2ba5e0bedf422ca8d884dac";
  }

  static const char* value(const ::face_read::SetParameters&) { return value(); }
};

template<>
struct DataType< ::face_read::SetParameters > {
  static const char* value()
  {
    return "face_read/SetParameters";
  }

  static const char* value(const ::face_read::SetParameters&) { return value(); }
};


// service_traits::MD5Sum< ::face_read::SetParametersRequest> should match
// service_traits::MD5Sum< ::face_read::SetParameters >
template<>
struct MD5Sum< ::face_read::SetParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::face_read::SetParameters >::value();
  }
  static const char* value(const ::face_read::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_read::SetParametersRequest> should match
// service_traits::DataType< ::face_read::SetParameters >
template<>
struct DataType< ::face_read::SetParametersRequest>
{
  static const char* value()
  {
    return DataType< ::face_read::SetParameters >::value();
  }
  static const char* value(const ::face_read::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::face_read::SetParametersResponse> should match
// service_traits::MD5Sum< ::face_read::SetParameters >
template<>
struct MD5Sum< ::face_read::SetParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::face_read::SetParameters >::value();
  }
  static const char* value(const ::face_read::SetParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_read::SetParametersResponse> should match
// service_traits::DataType< ::face_read::SetParameters >
template<>
struct DataType< ::face_read::SetParametersResponse>
{
  static const char* value()
  {
    return DataType< ::face_read::SetParameters >::value();
  }
  static const char* value(const ::face_read::SetParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACE_READ_MESSAGE_SETPARAMETERS_H
