(cl:defpackage action_demo-msg
  (:use )
  (:export
   "<ACTTESTACTION>"
   "ACTTESTACTION"
   "<ACTTESTACTIONFEEDBACK>"
   "ACTTESTACTIONFEEDBACK"
   "<ACTTESTACTIONGOAL>"
   "ACTTESTACTIONGOAL"
   "<ACTTESTACTIONRESULT>"
   "ACTTESTACTIONRESULT"
   "<ACTTESTFEEDBACK>"
   "ACTTESTFEEDBACK"
   "<ACTTESTGOAL>"
   "ACTTESTGOAL"
   "<ACTTESTRESULT>"
   "ACTTESTRESULT"
  ))

