; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude ActTestFeedback.msg.html

(cl:defclass <ActTestFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass ActTestFeedback (<ActTestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActTestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActTestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<ActTestFeedback> is deprecated: use action_demo-msg:ActTestFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <ActTestFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:progress-val is deprecated.  Use action_demo-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActTestFeedback>) ostream)
  "Serializes a message object of type '<ActTestFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActTestFeedback>) istream)
  "Deserializes a message object of type '<ActTestFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActTestFeedback>)))
  "Returns string type for a message object of type '<ActTestFeedback>"
  "action_demo/ActTestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActTestFeedback)))
  "Returns string type for a message object of type 'ActTestFeedback"
  "action_demo/ActTestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActTestFeedback>)))
  "Returns md5sum for a message object of type '<ActTestFeedback>"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActTestFeedback)))
  "Returns md5sum for a message object of type 'ActTestFeedback"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActTestFeedback>)))
  "Returns full string definition for message of type '<ActTestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActTestFeedback)))
  "Returns full string definition for message of type 'ActTestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActTestFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActTestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActTestFeedback
    (cl:cons ':progress (progress msg))
))
