// Auto-generated. Do not edit!

// (in-package central_proc.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CubeSolveExecFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.now_cmd = null;
    }
    else {
      if (initObj.hasOwnProperty('now_cmd')) {
        this.now_cmd = initObj.now_cmd
      }
      else {
        this.now_cmd = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CubeSolveExecFeedback
    // Serialize message field [now_cmd]
    bufferOffset = _serializer.string(obj.now_cmd, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CubeSolveExecFeedback
    let len;
    let data = new CubeSolveExecFeedback(null);
    // Deserialize message field [now_cmd]
    data.now_cmd = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.now_cmd);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'central_proc/CubeSolveExecFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8e4a40387680c99bba0920b8846eec59';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    # 定义周期反馈的信息
    string now_cmd
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CubeSolveExecFeedback(null);
    if (msg.now_cmd !== undefined) {
      resolved.now_cmd = msg.now_cmd;
    }
    else {
      resolved.now_cmd = ''
    }

    return resolved;
    }
};

module.exports = CubeSolveExecFeedback;
