// Auto-generated. Do not edit!

// (in-package central_proc.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CubeSolveExecGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cmd_list = null;
    }
    else {
      if (initObj.hasOwnProperty('cmd_list')) {
        this.cmd_list = initObj.cmd_list
      }
      else {
        this.cmd_list = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CubeSolveExecGoal
    // Serialize message field [cmd_list]
    bufferOffset = _serializer.string(obj.cmd_list, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CubeSolveExecGoal
    let len;
    let data = new CubeSolveExecGoal(null);
    // Deserialize message field [cmd_list]
    data.cmd_list = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.cmd_list);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'central_proc/CubeSolveExecGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b1c785ab2e1e6a0b11bd87ebff35a4c4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    # 定义目标信息
    string cmd_list
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CubeSolveExecGoal(null);
    if (msg.cmd_list !== undefined) {
      resolved.cmd_list = msg.cmd_list;
    }
    else {
      resolved.cmd_list = ''
    }

    return resolved;
    }
};

module.exports = CubeSolveExecGoal;
