// Auto-generated. Do not edit!

// (in-package central_proc.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CubeReadExecFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.now_read_faces = null;
    }
    else {
      if (initObj.hasOwnProperty('now_read_faces')) {
        this.now_read_faces = initObj.now_read_faces
      }
      else {
        this.now_read_faces = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CubeReadExecFeedback
    // Serialize message field [now_read_faces]
    bufferOffset = _serializer.string(obj.now_read_faces, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CubeReadExecFeedback
    let len;
    let data = new CubeReadExecFeedback(null);
    // Deserialize message field [now_read_faces]
    data.now_read_faces = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.now_read_faces);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'central_proc/CubeReadExecFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '699f435aa7ac3cfafcb50b8cb4e74a34';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    # 定义周期反馈的信息
    string now_read_faces
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CubeReadExecFeedback(null);
    if (msg.now_read_faces !== undefined) {
      resolved.now_read_faces = msg.now_read_faces;
    }
    else {
      resolved.now_read_faces = ''
    }

    return resolved;
    }
};

module.exports = CubeReadExecFeedback;
