// Auto-generated. Do not edit!

// (in-package central_proc.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CubeReadExecResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.six_faces_str = null;
      this.hand_axis = null;
    }
    else {
      if (initObj.hasOwnProperty('six_faces_str')) {
        this.six_faces_str = initObj.six_faces_str
      }
      else {
        this.six_faces_str = '';
      }
      if (initObj.hasOwnProperty('hand_axis')) {
        this.hand_axis = initObj.hand_axis
      }
      else {
        this.hand_axis = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CubeReadExecResult
    // Serialize message field [six_faces_str]
    bufferOffset = _serializer.string(obj.six_faces_str, buffer, bufferOffset);
    // Serialize message field [hand_axis]
    bufferOffset = _serializer.string(obj.hand_axis, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CubeReadExecResult
    let len;
    let data = new CubeReadExecResult(null);
    // Deserialize message field [six_faces_str]
    data.six_faces_str = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [hand_axis]
    data.hand_axis = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.six_faces_str);
    length += _getByteLength(object.hand_axis);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'central_proc/CubeReadExecResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '134c9d0d676cc6167f6852a290879bdd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    # 定义结果信息
    string six_faces_str
    string hand_axis
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CubeReadExecResult(null);
    if (msg.six_faces_str !== undefined) {
      resolved.six_faces_str = msg.six_faces_str;
    }
    else {
      resolved.six_faces_str = ''
    }

    if (msg.hand_axis !== undefined) {
      resolved.hand_axis = msg.hand_axis;
    }
    else {
      resolved.hand_axis = ''
    }

    return resolved;
    }
};

module.exports = CubeReadExecResult;
