(cl:defpackage face_read-srv
  (:use )
  (:export
   "GETPARAMETERS"
   "<GETPARAMETERS-REQUEST>"
   "GETPARAMETERS-REQUEST"
   "<GETPARAMETERS-RESPONSE>"
   "GETPARAMETERS-RESPONSE"
   "READTWOFACES"
   "<READTWOFACES-REQUEST>"
   "READTWOFACES-REQUEST"
   "<READTWOFACES-RESPONSE>"
   "READTWOFACES-RESPONSE"
   "SETPARAMETERS"
   "<SETPARAMETERS-REQUEST>"
   "SETPARAMETERS-REQUEST"
   "<SETPARAMETERS-RESPONSE>"
   "SETPARAMETERS-RESPONSE"
  ))

