(cl:defpackage kociemba_solve-srv
  (:use )
  (:export
   "KOCIEMBASOLVE"
   "<KOCIEMBASOLVE-REQUEST>"
   "KOCIEMBASOLVE-REQUEST"
   "<KOCIEMBASOLVE-RESPONSE>"
   "KOCIEMBASOLVE-RESPONSE"
   "RANDOMSOLVE"
   "<RANDOMSOLVE-REQUEST>"
   "RANDOMSOLVE-REQUEST"
   "<RANDOMSOLVE-RESPONSE>"
   "RANDOMSOLVE-RESPONSE"
  ))

