// Auto-generated. Do not edit!

// (in-package action_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ActTestGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.step_num = null;
    }
    else {
      if (initObj.hasOwnProperty('step_num')) {
        this.step_num = initObj.step_num
      }
      else {
        this.step_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ActTestGoal
    // Serialize message field [step_num]
    bufferOffset = _serializer.uint16(obj.step_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ActTestGoal
    let len;
    let data = new ActTestGoal(null);
    // Deserialize message field [step_num]
    data.step_num = _deserializer.uint16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_demo/ActTestGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9887d69f974ffe6cc0219745fb2fdaf5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint16 step_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ActTestGoal(null);
    if (msg.step_num !== undefined) {
      resolved.step_num = msg.step_num;
    }
    else {
      resolved.step_num = 0
    }

    return resolved;
    }
};

module.exports = ActTestGoal;
