; Auto-generated. Do not edit!


(cl:in-package central_proc-msg)


;//! \htmlinclude CubeSolveExecGoal.msg.html

(cl:defclass <CubeSolveExecGoal> (roslisp-msg-protocol:ros-message)
  ((cmd_list
    :reader cmd_list
    :initarg :cmd_list
    :type cl:string
    :initform ""))
)

(cl:defclass CubeSolveExecGoal (<CubeSolveExecGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CubeSolveExecGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CubeSolveExecGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name central_proc-msg:<CubeSolveExecGoal> is deprecated: use central_proc-msg:CubeSolveExecGoal instead.")))

(cl:ensure-generic-function 'cmd_list-val :lambda-list '(m))
(cl:defmethod cmd_list-val ((m <CubeSolveExecGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:cmd_list-val is deprecated.  Use central_proc-msg:cmd_list instead.")
  (cmd_list m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CubeSolveExecGoal>) ostream)
  "Serializes a message object of type '<CubeSolveExecGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'cmd_list))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'cmd_list))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CubeSolveExecGoal>) istream)
  "Deserializes a message object of type '<CubeSolveExecGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cmd_list) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'cmd_list) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CubeSolveExecGoal>)))
  "Returns string type for a message object of type '<CubeSolveExecGoal>"
  "central_proc/CubeSolveExecGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CubeSolveExecGoal)))
  "Returns string type for a message object of type 'CubeSolveExecGoal"
  "central_proc/CubeSolveExecGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CubeSolveExecGoal>)))
  "Returns md5sum for a message object of type '<CubeSolveExecGoal>"
  "b1c785ab2e1e6a0b11bd87ebff35a4c4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CubeSolveExecGoal)))
  "Returns md5sum for a message object of type 'CubeSolveExecGoal"
  "b1c785ab2e1e6a0b11bd87ebff35a4c4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CubeSolveExecGoal>)))
  "Returns full string definition for message of type '<CubeSolveExecGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%# 定义目标信息~%string cmd_list~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CubeSolveExecGoal)))
  "Returns full string definition for message of type 'CubeSolveExecGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%# 定义目标信息~%string cmd_list~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CubeSolveExecGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'cmd_list))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CubeSolveExecGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CubeSolveExecGoal
    (cl:cons ':cmd_list (cmd_list msg))
))
