; Auto-generated. Do not edit!


(cl:in-package central_proc-msg)


;//! \htmlinclude CubeReadExecResult.msg.html

(cl:defclass <CubeReadExecResult> (roslisp-msg-protocol:ros-message)
  ((six_faces_str
    :reader six_faces_str
    :initarg :six_faces_str
    :type cl:string
    :initform "")
   (hand_axis
    :reader hand_axis
    :initarg :hand_axis
    :type cl:string
    :initform ""))
)

(cl:defclass CubeReadExecResult (<CubeReadExecResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CubeReadExecResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CubeReadExecResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name central_proc-msg:<CubeReadExecResult> is deprecated: use central_proc-msg:CubeReadExecResult instead.")))

(cl:ensure-generic-function 'six_faces_str-val :lambda-list '(m))
(cl:defmethod six_faces_str-val ((m <CubeReadExecResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:six_faces_str-val is deprecated.  Use central_proc-msg:six_faces_str instead.")
  (six_faces_str m))

(cl:ensure-generic-function 'hand_axis-val :lambda-list '(m))
(cl:defmethod hand_axis-val ((m <CubeReadExecResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:hand_axis-val is deprecated.  Use central_proc-msg:hand_axis instead.")
  (hand_axis m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CubeReadExecResult>) ostream)
  "Serializes a message object of type '<CubeReadExecResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'six_faces_str))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'six_faces_str))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'hand_axis))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'hand_axis))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CubeReadExecResult>) istream)
  "Deserializes a message object of type '<CubeReadExecResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'six_faces_str) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'six_faces_str) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'hand_axis) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'hand_axis) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CubeReadExecResult>)))
  "Returns string type for a message object of type '<CubeReadExecResult>"
  "central_proc/CubeReadExecResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CubeReadExecResult)))
  "Returns string type for a message object of type 'CubeReadExecResult"
  "central_proc/CubeReadExecResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CubeReadExecResult>)))
  "Returns md5sum for a message object of type '<CubeReadExecResult>"
  "134c9d0d676cc6167f6852a290879bdd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CubeReadExecResult)))
  "Returns md5sum for a message object of type 'CubeReadExecResult"
  "134c9d0d676cc6167f6852a290879bdd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CubeReadExecResult>)))
  "Returns full string definition for message of type '<CubeReadExecResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%# 定义结果信息~%string six_faces_str~%string hand_axis~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CubeReadExecResult)))
  "Returns full string definition for message of type 'CubeReadExecResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%# 定义结果信息~%string six_faces_str~%string hand_axis~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CubeReadExecResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'six_faces_str))
     4 (cl:length (cl:slot-value msg 'hand_axis))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CubeReadExecResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CubeReadExecResult
    (cl:cons ':six_faces_str (six_faces_str msg))
    (cl:cons ':hand_axis (hand_axis msg))
))
