; Auto-generated. Do not edit!


(cl:in-package central_proc-msg)


;//! \htmlinclude CubeReadExecGoal.msg.html

(cl:defclass <CubeReadExecGoal> (roslisp-msg-protocol:ros-message)
  ((read_mode
    :reader read_mode
    :initarg :read_mode
    :type cl:string
    :initform ""))
)

(cl:defclass CubeReadExecGoal (<CubeReadExecGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CubeReadExecGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CubeReadExecGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name central_proc-msg:<CubeReadExecGoal> is deprecated: use central_proc-msg:CubeReadExecGoal instead.")))

(cl:ensure-generic-function 'read_mode-val :lambda-list '(m))
(cl:defmethod read_mode-val ((m <CubeReadExecGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:read_mode-val is deprecated.  Use central_proc-msg:read_mode instead.")
  (read_mode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CubeReadExecGoal>) ostream)
  "Serializes a message object of type '<CubeReadExecGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'read_mode))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'read_mode))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CubeReadExecGoal>) istream)
  "Deserializes a message object of type '<CubeReadExecGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'read_mode) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'read_mode) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CubeReadExecGoal>)))
  "Returns string type for a message object of type '<CubeReadExecGoal>"
  "central_proc/CubeReadExecGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CubeReadExecGoal)))
  "Returns string type for a message object of type 'CubeReadExecGoal"
  "central_proc/CubeReadExecGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CubeReadExecGoal>)))
  "Returns md5sum for a message object of type '<CubeReadExecGoal>"
  "d133e27424af94de682501d23720b86f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CubeReadExecGoal)))
  "Returns md5sum for a message object of type 'CubeReadExecGoal"
  "d133e27424af94de682501d23720b86f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CubeReadExecGoal>)))
  "Returns full string definition for message of type '<CubeReadExecGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 读取模式~%string read_mode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CubeReadExecGoal)))
  "Returns full string definition for message of type 'CubeReadExecGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 读取模式~%string read_mode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CubeReadExecGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'read_mode))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CubeReadExecGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CubeReadExecGoal
    (cl:cons ':read_mode (read_mode msg))
))
