; Auto-generated. Do not edit!


(cl:in-package central_proc-msg)


;//! \htmlinclude CubeReadExecFeedback.msg.html

(cl:defclass <CubeReadExecFeedback> (roslisp-msg-protocol:ros-message)
  ((now_read_faces
    :reader now_read_faces
    :initarg :now_read_faces
    :type cl:string
    :initform ""))
)

(cl:defclass CubeReadExecFeedback (<CubeReadExecFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CubeReadExecFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CubeReadExecFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name central_proc-msg:<CubeReadExecFeedback> is deprecated: use central_proc-msg:CubeReadExecFeedback instead.")))

(cl:ensure-generic-function 'now_read_faces-val :lambda-list '(m))
(cl:defmethod now_read_faces-val ((m <CubeReadExecFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:now_read_faces-val is deprecated.  Use central_proc-msg:now_read_faces instead.")
  (now_read_faces m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CubeReadExecFeedback>) ostream)
  "Serializes a message object of type '<CubeReadExecFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'now_read_faces))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'now_read_faces))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CubeReadExecFeedback>) istream)
  "Deserializes a message object of type '<CubeReadExecFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'now_read_faces) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'now_read_faces) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CubeReadExecFeedback>)))
  "Returns string type for a message object of type '<CubeReadExecFeedback>"
  "central_proc/CubeReadExecFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CubeReadExecFeedback)))
  "Returns string type for a message object of type 'CubeReadExecFeedback"
  "central_proc/CubeReadExecFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CubeReadExecFeedback>)))
  "Returns md5sum for a message object of type '<CubeReadExecFeedback>"
  "699f435aa7ac3cfafcb50b8cb4e74a34")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CubeReadExecFeedback)))
  "Returns md5sum for a message object of type 'CubeReadExecFeedback"
  "699f435aa7ac3cfafcb50b8cb4e74a34")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CubeReadExecFeedback>)))
  "Returns full string definition for message of type '<CubeReadExecFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# 定义周期反馈的信息~%string now_read_faces~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CubeReadExecFeedback)))
  "Returns full string definition for message of type 'CubeReadExecFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# 定义周期反馈的信息~%string now_read_faces~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CubeReadExecFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'now_read_faces))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CubeReadExecFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CubeReadExecFeedback
    (cl:cons ':now_read_faces (now_read_faces msg))
))
