; Auto-generated. Do not edit!


(cl:in-package central_proc-msg)


;//! \htmlinclude CubeSolveExecFeedback.msg.html

(cl:defclass <CubeSolveExecFeedback> (roslisp-msg-protocol:ros-message)
  ((now_cmd
    :reader now_cmd
    :initarg :now_cmd
    :type cl:string
    :initform ""))
)

(cl:defclass CubeSolveExecFeedback (<CubeSolveExecFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CubeSolveExecFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CubeSolveExecFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name central_proc-msg:<CubeSolveExecFeedback> is deprecated: use central_proc-msg:CubeSolveExecFeedback instead.")))

(cl:ensure-generic-function 'now_cmd-val :lambda-list '(m))
(cl:defmethod now_cmd-val ((m <CubeSolveExecFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader central_proc-msg:now_cmd-val is deprecated.  Use central_proc-msg:now_cmd instead.")
  (now_cmd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CubeSolveExecFeedback>) ostream)
  "Serializes a message object of type '<CubeSolveExecFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'now_cmd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'now_cmd))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CubeSolveExecFeedback>) istream)
  "Deserializes a message object of type '<CubeSolveExecFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'now_cmd) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'now_cmd) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CubeSolveExecFeedback>)))
  "Returns string type for a message object of type '<CubeSolveExecFeedback>"
  "central_proc/CubeSolveExecFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CubeSolveExecFeedback)))
  "Returns string type for a message object of type 'CubeSolveExecFeedback"
  "central_proc/CubeSolveExecFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CubeSolveExecFeedback>)))
  "Returns md5sum for a message object of type '<CubeSolveExecFeedback>"
  "8e4a40387680c99bba0920b8846eec59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CubeSolveExecFeedback)))
  "Returns md5sum for a message object of type 'CubeSolveExecFeedback"
  "8e4a40387680c99bba0920b8846eec59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CubeSolveExecFeedback>)))
  "Returns full string definition for message of type '<CubeSolveExecFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# 定义周期反馈的信息~%string now_cmd~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CubeSolveExecFeedback)))
  "Returns full string definition for message of type 'CubeSolveExecFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# 定义周期反馈的信息~%string now_cmd~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CubeSolveExecFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'now_cmd))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CubeSolveExecFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CubeSolveExecFeedback
    (cl:cons ':now_cmd (now_cmd msg))
))
