// Generated by gencpp from file path_planning/PathPlanning.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MESSAGE_PATHPLANNING_H
#define PATH_PLANNING_MESSAGE_PATHPLANNING_H

#include <ros/service_traits.h>


#include <path_planning/PathPlanningRequest.h>
#include <path_planning/PathPlanningResponse.h>


namespace path_planning
{

struct PathPlanning
{

typedef PathPlanningRequest Request;
typedef PathPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlanning
} // namespace path_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planning::PathPlanning > {
  static const char* value()
  {
    return "1eee7119fb9bc2458d0167605d08766d";
  }

  static const char* value(const ::path_planning::PathPlanning&) { return value(); }
};

template<>
struct DataType< ::path_planning::PathPlanning > {
  static const char* value()
  {
    return "path_planning/PathPlanning";
  }

  static const char* value(const ::path_planning::PathPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::path_planning::PathPlanningRequest> should match
// service_traits::MD5Sum< ::path_planning::PathPlanning >
template<>
struct MD5Sum< ::path_planning::PathPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planning::PathPlanning >::value();
  }
  static const char* value(const ::path_planning::PathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planning::PathPlanningRequest> should match
// service_traits::DataType< ::path_planning::PathPlanning >
template<>
struct DataType< ::path_planning::PathPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::path_planning::PathPlanning >::value();
  }
  static const char* value(const ::path_planning::PathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planning::PathPlanningResponse> should match
// service_traits::MD5Sum< ::path_planning::PathPlanning >
template<>
struct MD5Sum< ::path_planning::PathPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planning::PathPlanning >::value();
  }
  static const char* value(const ::path_planning::PathPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planning::PathPlanningResponse> should match
// service_traits::DataType< ::path_planning::PathPlanning >
template<>
struct DataType< ::path_planning::PathPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::path_planning::PathPlanning >::value();
  }
  static const char* value(const ::path_planning::PathPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNING_MESSAGE_PATHPLANNING_H
