// Generated by gencpp from file kociemba_solve/KociembaSolveRequest.msg
// DO NOT EDIT!


#ifndef KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVEREQUEST_H
#define KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kociemba_solve
{
template <class ContainerAllocator>
struct KociembaSolveRequest_
{
  typedef KociembaSolveRequest_<ContainerAllocator> Type;

  KociembaSolveRequest_()
    : six_face_str()  {
    }
  KociembaSolveRequest_(const ContainerAllocator& _alloc)
    : six_face_str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _six_face_str_type;
  _six_face_str_type six_face_str;





  typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KociembaSolveRequest_

typedef ::kociemba_solve::KociembaSolveRequest_<std::allocator<void> > KociembaSolveRequest;

typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveRequest > KociembaSolveRequestPtr;
typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveRequest const> KociembaSolveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator1> & lhs, const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.six_face_str == rhs.six_face_str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator1> & lhs, const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kociemba_solve

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb54d8370dea95c40a6a0b3161f627c9";
  }

  static const char* value(const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb54d8370dea95c4ULL;
  static const uint64_t static_value2 = 0x0a6a0b3161f627c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kociemba_solve/KociembaSolveRequest";
  }

  static const char* value(const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string six_face_str\n"
;
  }

  static const char* value(const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.six_face_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KociembaSolveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kociemba_solve::KociembaSolveRequest_<ContainerAllocator>& v)
  {
    s << indent << "six_face_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.six_face_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVEREQUEST_H
