// Generated by gencpp from file kociemba_solve/KociembaSolve.msg
// DO NOT EDIT!


#ifndef KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVE_H
#define KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVE_H

#include <ros/service_traits.h>


#include <kociemba_solve/KociembaSolveRequest.h>
#include <kociemba_solve/KociembaSolveResponse.h>


namespace kociemba_solve
{

struct KociembaSolve
{

typedef KociembaSolveRequest Request;
typedef KociembaSolveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KociembaSolve
} // namespace kociemba_solve


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kociemba_solve::KociembaSolve > {
  static const char* value()
  {
    return "2dda5a023a8b634c158eca12da32426c";
  }

  static const char* value(const ::kociemba_solve::KociembaSolve&) { return value(); }
};

template<>
struct DataType< ::kociemba_solve::KociembaSolve > {
  static const char* value()
  {
    return "kociemba_solve/KociembaSolve";
  }

  static const char* value(const ::kociemba_solve::KociembaSolve&) { return value(); }
};


// service_traits::MD5Sum< ::kociemba_solve::KociembaSolveRequest> should match
// service_traits::MD5Sum< ::kociemba_solve::KociembaSolve >
template<>
struct MD5Sum< ::kociemba_solve::KociembaSolveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kociemba_solve::KociembaSolve >::value();
  }
  static const char* value(const ::kociemba_solve::KociembaSolveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kociemba_solve::KociembaSolveRequest> should match
// service_traits::DataType< ::kociemba_solve::KociembaSolve >
template<>
struct DataType< ::kociemba_solve::KociembaSolveRequest>
{
  static const char* value()
  {
    return DataType< ::kociemba_solve::KociembaSolve >::value();
  }
  static const char* value(const ::kociemba_solve::KociembaSolveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kociemba_solve::KociembaSolveResponse> should match
// service_traits::MD5Sum< ::kociemba_solve::KociembaSolve >
template<>
struct MD5Sum< ::kociemba_solve::KociembaSolveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kociemba_solve::KociembaSolve >::value();
  }
  static const char* value(const ::kociemba_solve::KociembaSolveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kociemba_solve::KociembaSolveResponse> should match
// service_traits::DataType< ::kociemba_solve::KociembaSolve >
template<>
struct DataType< ::kociemba_solve::KociembaSolveResponse>
{
  static const char* value()
  {
    return DataType< ::kociemba_solve::KociembaSolve >::value();
  }
  static const char* value(const ::kociemba_solve::KociembaSolveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVE_H
