// Generated by gencpp from file kociemba_solve/KociembaSolveResponse.msg
// DO NOT EDIT!


#ifndef KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVERESPONSE_H
#define KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kociemba_solve
{
template <class ContainerAllocator>
struct KociembaSolveResponse_
{
  typedef KociembaSolveResponse_<ContainerAllocator> Type;

  KociembaSolveResponse_()
    : solve_str()  {
    }
  KociembaSolveResponse_(const ContainerAllocator& _alloc)
    : solve_str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _solve_str_type;
  _solve_str_type solve_str;





  typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct KociembaSolveResponse_

typedef ::kociemba_solve::KociembaSolveResponse_<std::allocator<void> > KociembaSolveResponse;

typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveResponse > KociembaSolveResponsePtr;
typedef boost::shared_ptr< ::kociemba_solve::KociembaSolveResponse const> KociembaSolveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator1> & lhs, const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.solve_str == rhs.solve_str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator1> & lhs, const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kociemba_solve

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac23f95809f2e14e3143946f779d7d45";
  }

  static const char* value(const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac23f95809f2e14eULL;
  static const uint64_t static_value2 = 0x3143946f779d7d45ULL;
};

template<class ContainerAllocator>
struct DataType< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kociemba_solve/KociembaSolveResponse";
  }

  static const char* value(const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string solve_str\n"
"\n"
;
  }

  static const char* value(const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solve_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KociembaSolveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kociemba_solve::KociembaSolveResponse_<ContainerAllocator>& v)
  {
    s << indent << "solve_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.solve_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCIEMBA_SOLVE_MESSAGE_KOCIEMBASOLVERESPONSE_H
