// Generated by gencpp from file kociemba_solve/RandomSolveResponse.msg
// DO NOT EDIT!


#ifndef KOCIEMBA_SOLVE_MESSAGE_RANDOMSOLVERESPONSE_H
#define KOCIEMBA_SOLVE_MESSAGE_RANDOMSOLVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kociemba_solve
{
template <class ContainerAllocator>
struct RandomSolveResponse_
{
  typedef RandomSolveResponse_<ContainerAllocator> Type;

  RandomSolveResponse_()
    : random_str()  {
    }
  RandomSolveResponse_(const ContainerAllocator& _alloc)
    : random_str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _random_str_type;
  _random_str_type random_str;





  typedef boost::shared_ptr< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RandomSolveResponse_

typedef ::kociemba_solve::RandomSolveResponse_<std::allocator<void> > RandomSolveResponse;

typedef boost::shared_ptr< ::kociemba_solve::RandomSolveResponse > RandomSolveResponsePtr;
typedef boost::shared_ptr< ::kociemba_solve::RandomSolveResponse const> RandomSolveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator1> & lhs, const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.random_str == rhs.random_str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator1> & lhs, const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kociemba_solve

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c6c1fce66086563633ba1d124c1ee88";
  }

  static const char* value(const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c6c1fce66086563ULL;
  static const uint64_t static_value2 = 0x633ba1d124c1ee88ULL;
};

template<class ContainerAllocator>
struct DataType< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kociemba_solve/RandomSolveResponse";
  }

  static const char* value(const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string random_str\n"
"\n"
;
  }

  static const char* value(const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandomSolveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kociemba_solve::RandomSolveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kociemba_solve::RandomSolveResponse_<ContainerAllocator>& v)
  {
    s << indent << "random_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.random_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCIEMBA_SOLVE_MESSAGE_RANDOMSOLVERESPONSE_H
