// Generated by gencpp from file central_proc/CubeReadExecGoal.msg
// DO NOT EDIT!


#ifndef CENTRAL_PROC_MESSAGE_CUBEREADEXECGOAL_H
#define CENTRAL_PROC_MESSAGE_CUBEREADEXECGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace central_proc
{
template <class ContainerAllocator>
struct CubeReadExecGoal_
{
  typedef CubeReadExecGoal_<ContainerAllocator> Type;

  CubeReadExecGoal_()
    : read_mode()  {
    }
  CubeReadExecGoal_(const ContainerAllocator& _alloc)
    : read_mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _read_mode_type;
  _read_mode_type read_mode;





  typedef boost::shared_ptr< ::central_proc::CubeReadExecGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::central_proc::CubeReadExecGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CubeReadExecGoal_

typedef ::central_proc::CubeReadExecGoal_<std::allocator<void> > CubeReadExecGoal;

typedef boost::shared_ptr< ::central_proc::CubeReadExecGoal > CubeReadExecGoalPtr;
typedef boost::shared_ptr< ::central_proc::CubeReadExecGoal const> CubeReadExecGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::central_proc::CubeReadExecGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::central_proc::CubeReadExecGoal_<ContainerAllocator1> & lhs, const ::central_proc::CubeReadExecGoal_<ContainerAllocator2> & rhs)
{
  return lhs.read_mode == rhs.read_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::central_proc::CubeReadExecGoal_<ContainerAllocator1> & lhs, const ::central_proc::CubeReadExecGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace central_proc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeReadExecGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeReadExecGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeReadExecGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d133e27424af94de682501d23720b86f";
  }

  static const char* value(const ::central_proc::CubeReadExecGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd133e27424af94deULL;
  static const uint64_t static_value2 = 0x682501d23720b86fULL;
};

template<class ContainerAllocator>
struct DataType< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "central_proc/CubeReadExecGoal";
  }

  static const char* value(const ::central_proc::CubeReadExecGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 读取模式\n"
"string read_mode\n"
;
  }

  static const char* value(const ::central_proc::CubeReadExecGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.read_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeReadExecGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::central_proc::CubeReadExecGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::central_proc::CubeReadExecGoal_<ContainerAllocator>& v)
  {
    s << indent << "read_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.read_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTRAL_PROC_MESSAGE_CUBEREADEXECGOAL_H
