// Generated by gencpp from file central_proc/CubeSolveExecAction.msg
// DO NOT EDIT!


#ifndef CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTION_H
#define CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <central_proc/CubeSolveExecActionGoal.h>
#include <central_proc/CubeSolveExecActionResult.h>
#include <central_proc/CubeSolveExecActionFeedback.h>

namespace central_proc
{
template <class ContainerAllocator>
struct CubeSolveExecAction_
{
  typedef CubeSolveExecAction_<ContainerAllocator> Type;

  CubeSolveExecAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  CubeSolveExecAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::central_proc::CubeSolveExecActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::central_proc::CubeSolveExecActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::central_proc::CubeSolveExecAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::central_proc::CubeSolveExecAction_<ContainerAllocator> const> ConstPtr;

}; // struct CubeSolveExecAction_

typedef ::central_proc::CubeSolveExecAction_<std::allocator<void> > CubeSolveExecAction;

typedef boost::shared_ptr< ::central_proc::CubeSolveExecAction > CubeSolveExecActionPtr;
typedef boost::shared_ptr< ::central_proc::CubeSolveExecAction const> CubeSolveExecActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::central_proc::CubeSolveExecAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::central_proc::CubeSolveExecAction_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::central_proc::CubeSolveExecAction_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace central_proc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "941e514af3e07da21c183457c05111af";
  }

  static const char* value(const ::central_proc::CubeSolveExecAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x941e514af3e07da2ULL;
  static const uint64_t static_value2 = 0x1c183457c05111afULL;
};

template<class ContainerAllocator>
struct DataType< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "central_proc/CubeSolveExecAction";
  }

  static const char* value(const ::central_proc::CubeSolveExecAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"CubeSolveExecActionGoal action_goal\n"
"CubeSolveExecActionResult action_result\n"
"CubeSolveExecActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CubeSolveExecGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"# 定义目标信息\n"
"string cmd_list\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CubeSolveExecResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"# 定义结果信息\n"
"string result\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CubeSolveExecFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"# 定义周期反馈的信息\n"
"string now_cmd\n"
"\n"
;
  }

  static const char* value(const ::central_proc::CubeSolveExecAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeSolveExecAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::central_proc::CubeSolveExecAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::central_proc::CubeSolveExecAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::central_proc::CubeSolveExecActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::central_proc::CubeSolveExecActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTION_H
