// Generated by gencpp from file central_proc/CubeSolveExecResult.msg
// DO NOT EDIT!


#ifndef CENTRAL_PROC_MESSAGE_CUBESOLVEEXECRESULT_H
#define CENTRAL_PROC_MESSAGE_CUBESOLVEEXECRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace central_proc
{
template <class ContainerAllocator>
struct CubeSolveExecResult_
{
  typedef CubeSolveExecResult_<ContainerAllocator> Type;

  CubeSolveExecResult_()
    : result()  {
    }
  CubeSolveExecResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::central_proc::CubeSolveExecResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::central_proc::CubeSolveExecResult_<ContainerAllocator> const> ConstPtr;

}; // struct CubeSolveExecResult_

typedef ::central_proc::CubeSolveExecResult_<std::allocator<void> > CubeSolveExecResult;

typedef boost::shared_ptr< ::central_proc::CubeSolveExecResult > CubeSolveExecResultPtr;
typedef boost::shared_ptr< ::central_proc::CubeSolveExecResult const> CubeSolveExecResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::central_proc::CubeSolveExecResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::central_proc::CubeSolveExecResult_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::central_proc::CubeSolveExecResult_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace central_proc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::central_proc::CubeSolveExecResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "central_proc/CubeSolveExecResult";
  }

  static const char* value(const ::central_proc::CubeSolveExecResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"# 定义结果信息\n"
"string result\n"
;
  }

  static const char* value(const ::central_proc::CubeSolveExecResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeSolveExecResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::central_proc::CubeSolveExecResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::central_proc::CubeSolveExecResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTRAL_PROC_MESSAGE_CUBESOLVEEXECRESULT_H
