// Generated by gencpp from file central_proc/CubeSolveExecActionGoal.msg
// DO NOT EDIT!


#ifndef CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTIONGOAL_H
#define CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <central_proc/CubeSolveExecGoal.h>

namespace central_proc
{
template <class ContainerAllocator>
struct CubeSolveExecActionGoal_
{
  typedef CubeSolveExecActionGoal_<ContainerAllocator> Type;

  CubeSolveExecActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CubeSolveExecActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::central_proc::CubeSolveExecGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CubeSolveExecActionGoal_

typedef ::central_proc::CubeSolveExecActionGoal_<std::allocator<void> > CubeSolveExecActionGoal;

typedef boost::shared_ptr< ::central_proc::CubeSolveExecActionGoal > CubeSolveExecActionGoalPtr;
typedef boost::shared_ptr< ::central_proc::CubeSolveExecActionGoal const> CubeSolveExecActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator1> & lhs, const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace central_proc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "051f4925cd18936233dc37c021f2b5fb";
  }

  static const char* value(const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x051f4925cd189362ULL;
  static const uint64_t static_value2 = 0x33dc37c021f2b5fbULL;
};

template<class ContainerAllocator>
struct DataType< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "central_proc/CubeSolveExecActionGoal";
  }

  static const char* value(const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CubeSolveExecGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: central_proc/CubeSolveExecGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"# 定义目标信息\n"
"string cmd_list\n"
;
  }

  static const char* value(const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeSolveExecActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::central_proc::CubeSolveExecActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::central_proc::CubeSolveExecGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTRAL_PROC_MESSAGE_CUBESOLVEEXECACTIONGOAL_H
