// Generated by gencpp from file central_proc/CubeReadExecFeedback.msg
// DO NOT EDIT!


#ifndef CENTRAL_PROC_MESSAGE_CUBEREADEXECFEEDBACK_H
#define CENTRAL_PROC_MESSAGE_CUBEREADEXECFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace central_proc
{
template <class ContainerAllocator>
struct CubeReadExecFeedback_
{
  typedef CubeReadExecFeedback_<ContainerAllocator> Type;

  CubeReadExecFeedback_()
    : now_read_faces()  {
    }
  CubeReadExecFeedback_(const ContainerAllocator& _alloc)
    : now_read_faces(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _now_read_faces_type;
  _now_read_faces_type now_read_faces;





  typedef boost::shared_ptr< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CubeReadExecFeedback_

typedef ::central_proc::CubeReadExecFeedback_<std::allocator<void> > CubeReadExecFeedback;

typedef boost::shared_ptr< ::central_proc::CubeReadExecFeedback > CubeReadExecFeedbackPtr;
typedef boost::shared_ptr< ::central_proc::CubeReadExecFeedback const> CubeReadExecFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::central_proc::CubeReadExecFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::central_proc::CubeReadExecFeedback_<ContainerAllocator1> & lhs, const ::central_proc::CubeReadExecFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.now_read_faces == rhs.now_read_faces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::central_proc::CubeReadExecFeedback_<ContainerAllocator1> & lhs, const ::central_proc::CubeReadExecFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace central_proc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "699f435aa7ac3cfafcb50b8cb4e74a34";
  }

  static const char* value(const ::central_proc::CubeReadExecFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x699f435aa7ac3cfaULL;
  static const uint64_t static_value2 = 0xfcb50b8cb4e74a34ULL;
};

template<class ContainerAllocator>
struct DataType< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "central_proc/CubeReadExecFeedback";
  }

  static const char* value(const ::central_proc::CubeReadExecFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"# 定义周期反馈的信息\n"
"string now_read_faces\n"
;
  }

  static const char* value(const ::central_proc::CubeReadExecFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.now_read_faces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeReadExecFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::central_proc::CubeReadExecFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::central_proc::CubeReadExecFeedback_<ContainerAllocator>& v)
  {
    s << indent << "now_read_faces: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.now_read_faces);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTRAL_PROC_MESSAGE_CUBEREADEXECFEEDBACK_H
