// Generated by gencpp from file action_demo/ActTestFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_ACTTESTFEEDBACK_H
#define ACTION_DEMO_MESSAGE_ACTTESTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct ActTestFeedback_
{
  typedef ActTestFeedback_<ContainerAllocator> Type;

  ActTestFeedback_()
    : progress(0.0)  {
    }
  ActTestFeedback_(const ContainerAllocator& _alloc)
    : progress(0.0)  {
  (void)_alloc;
    }



   typedef float _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::action_demo::ActTestFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::ActTestFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActTestFeedback_

typedef ::action_demo::ActTestFeedback_<std::allocator<void> > ActTestFeedback;

typedef boost::shared_ptr< ::action_demo::ActTestFeedback > ActTestFeedbackPtr;
typedef boost::shared_ptr< ::action_demo::ActTestFeedback const> ActTestFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::ActTestFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::ActTestFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_demo::ActTestFeedback_<ContainerAllocator1> & lhs, const ::action_demo::ActTestFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_demo::ActTestFeedback_<ContainerAllocator1> & lhs, const ::action_demo::ActTestFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_demo::ActTestFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::ActTestFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::ActTestFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::ActTestFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::ActTestFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::ActTestFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::ActTestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70805092fd20e110765c7b79e8efb737";
  }

  static const char* value(const ::action_demo::ActTestFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70805092fd20e110ULL;
  static const uint64_t static_value2 = 0x765c7b79e8efb737ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::ActTestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/ActTestFeedback";
  }

  static const char* value(const ::action_demo::ActTestFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::ActTestFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 progress\n"
;
  }

  static const char* value(const ::action_demo::ActTestFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::ActTestFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActTestFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::ActTestFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::ActTestFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_ACTTESTFEEDBACK_H
