// Generated by gencpp from file action_demo/ActTestGoal.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_ACTTESTGOAL_H
#define ACTION_DEMO_MESSAGE_ACTTESTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct ActTestGoal_
{
  typedef ActTestGoal_<ContainerAllocator> Type;

  ActTestGoal_()
    : step_num(0)  {
    }
  ActTestGoal_(const ContainerAllocator& _alloc)
    : step_num(0)  {
  (void)_alloc;
    }



   typedef uint16_t _step_num_type;
  _step_num_type step_num;





  typedef boost::shared_ptr< ::action_demo::ActTestGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::ActTestGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ActTestGoal_

typedef ::action_demo::ActTestGoal_<std::allocator<void> > ActTestGoal;

typedef boost::shared_ptr< ::action_demo::ActTestGoal > ActTestGoalPtr;
typedef boost::shared_ptr< ::action_demo::ActTestGoal const> ActTestGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::ActTestGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::ActTestGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_demo::ActTestGoal_<ContainerAllocator1> & lhs, const ::action_demo::ActTestGoal_<ContainerAllocator2> & rhs)
{
  return lhs.step_num == rhs.step_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_demo::ActTestGoal_<ContainerAllocator1> & lhs, const ::action_demo::ActTestGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_demo::ActTestGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::ActTestGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::ActTestGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::ActTestGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::ActTestGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::ActTestGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::ActTestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9887d69f974ffe6cc0219745fb2fdaf5";
  }

  static const char* value(const ::action_demo::ActTestGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9887d69f974ffe6cULL;
  static const uint64_t static_value2 = 0xc0219745fb2fdaf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::ActTestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/ActTestGoal";
  }

  static const char* value(const ::action_demo::ActTestGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::ActTestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint16 step_num\n"
;
  }

  static const char* value(const ::action_demo::ActTestGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::ActTestGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActTestGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::ActTestGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::ActTestGoal_<ContainerAllocator>& v)
  {
    s << indent << "step_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.step_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_ACTTESTGOAL_H
